### ISSUE TITLE
建议:线程安全

### ISSUE THREAD

**Issue by dodola** [LittleFriendsGroup/KakaCache#1]
赞一个先.
大概看完了整个项目.建议在框架层就做好线程安全的考虑,因为缓存大部分的应用场景是一个缓存对一个线程池可见,一个缓存可能会有多个线程同时操作,这个同步最好不要抛给用户去处理,而且后面要做缓存命中率计算的话也会涉及到线程安全的问题,可能是项目刚起步还没来得及做,只是建议一下:blush:

**Comment by imkarl** [comment]
谢谢提醒，你的建议很好！
项目是有一个开发计划的，具体的计划表，稍后更新到Note.md备注。
大概的项目结构是这样：

```
common >> core >> manager >> netcache\imagecache
公用类 >> 存储核心 >> 缓存管理 >> 应用缓存
```
- **core** 实现数据的存储，不考虑线程等方面
- **manager** 实现缓存管理，包括但不限于线程等方面的管理
- **netcache**、**imagecache** 针对不同应用场景，做细节优化

有其他想法，欢迎继续留言～

**Comment by anjiao** [comment]
给力

**Comment by imkarl** [comment]
https://github.com/LittleFriendsGroup/KakaCache/blob/master/Note.md
已更新到Note.md

再次感谢各位大神的支持，鄙人见识有限，还晚各位多多提点。给点建议～
