### ISSUE TITLE
完善使用示例

### ISSUE THREAD

**Issue by weinierfei** [LittleFriendsGroup/KakaCache#3]
楼主辛苦,代码里没有说明这个库的用法,能不能添加个简单的示例?谢谢

**Comment by nukc** [comment]
@alafighting 出来说明一下吧，不要水遁了。

**Comment by imkarl** [comment]
目前还在填坑哦～
建议你参考下设计思路，代码结构。还有N多巨坑在填，马上会更新出来
这个项目的目标还是以学习研究为主，不是以实用为主。等到各方面细节基本完善了，会开通以实用为主的分支。
欢迎持续关注！

**Comment by weinierfei** [comment]
好的,感谢回复;持续关注中
