### ISSUE TITLE
这个不更了么?

### ISSUE THREAD

**Issue by weinierfei** [LittleFriendsGroup/KakaCache#5]
看见用rxjava的那个了,这个不更新了么?项目中不使用Retrofit和RxJava的,就不能用这个缓存方案么?

**Comment by imkarl** [comment]
更新！！
目前以实现特定技术下的方案为主，再反过来完善这个框架设计。
至少会支持RxJava、Callback两种方式，至于Sync的同步调用方式很可能会放弃了。

**Comment by weinierfei** [comment]
坐等更新
